// Copyright (c) Facebook, Inc. and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.

// Package logging is a generated GoMock package.
package logging

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSyslogWriter is a mock of SyslogWriter interface.
type MockSyslogWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSyslogWriterMockRecorder
	isgomock struct{}
}

// MockSyslogWriterMockRecorder is the mock recorder for MockSyslogWriter.
type MockSyslogWriterMockRecorder struct {
	mock *MockSyslogWriter
}

// NewMockSyslogWriter creates a new mock instance.
func NewMockSyslogWriter(ctrl *gomock.Controller) *MockSyslogWriter {
	mock := &MockSyslogWriter{ctrl: ctrl}
	mock.recorder = &MockSyslogWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyslogWriter) EXPECT() *MockSyslogWriterMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m_2 *MockSyslogWriter) Debug(m string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Debug", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Debug indicates an expected call of Debug.
func (mr *MockSyslogWriterMockRecorder) Debug(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockSyslogWriter)(nil).Debug), m)
}

// Err mocks base method.
func (m_2 *MockSyslogWriter) Err(m string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Err", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockSyslogWriterMockRecorder) Err(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockSyslogWriter)(nil).Err), m)
}

// Info mocks base method.
func (m_2 *MockSyslogWriter) Info(m string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Info", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockSyslogWriterMockRecorder) Info(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockSyslogWriter)(nil).Info), m)
}

// Warning mocks base method.
func (m_2 *MockSyslogWriter) Warning(m string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Warning", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Warning indicates an expected call of Warning.
func (mr *MockSyslogWriterMockRecorder) Warning(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warning", reflect.TypeOf((*MockSyslogWriter)(nil).Warning), m)
}
